
name: Lint

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 16.18.1
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Packages
        run: make node_modules
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: make do-lint

      - name: Build
        run: make dist
  
