
name: Lint

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 16.18.1
          registry-url: 'https://npm.pkg.github.com'

      - name: Write private key to .npmrc file
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install Packages
        run: npm install

      - name: Lint
        run: npm run eslint src

      - name: Build
        run: npm run tsc
  
