
name: Lint

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Node Version
        run: echo "NODE_VERSION=$(jq -crM .engines.node < package.json)" >> $GITHUB_OUTPUT
        shell: bash
        id: node_version

      - name: Use Node.js ${{ steps.node_version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.node_version.outputs.NODE_VERSION }}'
          cache: 'npm'

      - name: Install Packages
        run: npm install

      - name: Lint
        run: npm run eslint src

      - name: Build
        run: npm run tsc
  
