name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Read Node Version
        id: node_version
        run: echo "NODE_VERSION=$(jq -crM .engines.node < package.json)" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v7
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Packages
        run: make node_modules
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: make do-lint

      - name: Build
        run: make dist
  
