
name: Package Publish

on:
  push:
    branches:
     - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 20.18.0
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Packages
        run: make node_modules
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: make do-lint

      - name: Build
        run: make dist

      - name: Check version changes
        uses: EndBug/version-check@eea9dab124be9214bd32356f32f7d8945173db13 # v1
        id: check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: Publish Package
        if: steps.check.outputs.changed == 'true'
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
